#CC := i686-pc-mingw32-gcc

MKBOOTIMG_SRC_FILES := mkbootimg.c sha.c
MKBOOTIMG_OBJ_FILES := $(MKBOOTIMG_SRC_FILES:%.c=%.o)
MKBOOTIMG := mkbootimg.exe

UNPACKBOOTIMG_SRC_FILES := unpackbootimg.c
UNPACKBOOTIMG_OBJ_FILES := $(UNPACKBOOTIMG_SRC_FILES:%.c=%.o)
UNPACKBOOTIMG := unpackbootimg.exe

MKBOOTFS_SRC_FILES := mkbootfs.c
MKBOOTFS_OBJ_FILES := $(MKBOOTFS_SRC_FILES:%.c=%.o)
MKBOOTFS := mkbootfs.exe

LDFLAGS :=  
CFLAGS := -Iinclude
# -Werror 
all: $(MKBOOTIMG) $(UNPACKBOOTIMG) $(MKBOOTFS) 

$(MKBOOTIMG): $(MKBOOTIMG_OBJ_FILES)
	$(CC) -o $@ $^ $(LDFLAGS)

$(UNPACKBOOTIMG): $(UNPACKBOOTIMG_OBJ_FILES)
	$(CC) -o $@ $^ $(LDFLAGS)

$(MKBOOTFS): $(MKBOOTFS_OBJ_FILES)
	$(CC) -o $@ $^ $(LDFLAGS)

clean: 
	$(RM) $(MKBOOTIMG_OBJ_FILES) $(MKBOOTIMG) \
	$(UNPACKBOOTIMG_OBJ_FILES) $(UNPACKBOOTIMG) \
	$(MKBOOTFS_OBJ_FILES) $(MKBOOTFS)
